include: package:flutter_lints/flutter.yaml

formatter: 
  page_width: 80

linter:  
  rules:
    avoid_print: false
    always_specify_types: true
    always_use_package_imports: true
    directives_ordering: true