import 'package:csm_view/csm_view.dart';
import 'package:flutter/foundation.dart';
import 'package:go_router/go_router.dart';

/// [Router] Application router dependency.
final Router _router = Router.i;

/// [Model] class for [RouteData].
///
/// Defines a data structure for the current [Route] information being requested by the
/// user and is being built.
final class RouteData {
  /// Details about the [Route] requested.
  final Route route;

  /// Absolute route tree (web path).
  final String absolutePath;

  /// Unique generated key (this is automatically generated by the native framework router [GoRouter]).
  final ValueKey<String>? pageKey;

  /// Generates a new [RouteData] instance.
  const RouteData({
    this.pageKey,
    required this.route,
    required this.absolutePath,
  });

  /// Generates a new [RouteData] instance.
  ///
  /// Based on the native framework ([GoRouter]) operation metadata result, and
  /// development time specified [Route].
  factory RouteData.fromGo(GoRouterState goState, Route route) {
    String? absolutePath = _router.getAbsolutePath(route);

    return RouteData(
      route: route,
      pageKey: goState.pageKey,
      absolutePath: absolutePath,
    );
  }
}
